name: Scala CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - name: Build and run tests
        run: sbt clean compile cards-app / test cards-app / docker:publishLocal cards-app-tests / test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - name: Formatting
        run: sbt scalafmtCheck test:scalafmtCheck