name: Scala CI
on:
  push:
    branches:
      - main
      - 'homework/*'
  pull_request:
    branches:
      - main
      - 'homework/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - name: Build and run tests
        run: sbt clean compile test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        run: sbt scalafmtCheck test:scalafmtCheck